// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Seguros.API.Data;

#nullable disable

namespace api_test.Migrations
{
    [DbContext(typeof(SegurosDbContext))]
    [Migration("20251128171455_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Seguros.API.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Identidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoCliente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ClienteId");

                    b.HasIndex("Identidad")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Seguros.API.Models.Cotizacion", b =>
                {
                    b.Property<int>("CotizacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CotizacionId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionBien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCotizacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NumeroCotizacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("SumaAsegurada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tasa")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TipoSeguroId")
                        .HasColumnType("int");

                    b.HasKey("CotizacionId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FechaCotizacion");

                    b.HasIndex("NumeroCotizacion")
                        .IsUnique();

                    b.HasIndex("TipoSeguroId");

                    b.ToTable("Cotizaciones");
                });

            modelBuilder.Entity("Seguros.API.Models.TipoSeguro", b =>
                {
                    b.Property<int>("TipoSeguroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoSeguroId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TipoSeguroId");

                    b.ToTable("TiposSeguro");

                    b.HasData(
                        new
                        {
                            TipoSeguroId = 1,
                            Descripcion = "Seguro médico general",
                            Nombre = "Médico"
                        },
                        new
                        {
                            TipoSeguroId = 2,
                            Descripcion = "Seguro para vehículos",
                            Nombre = "Automóvil"
                        },
                        new
                        {
                            TipoSeguroId = 3,
                            Descripcion = "Seguro contra incendios",
                            Nombre = "Incendio"
                        },
                        new
                        {
                            TipoSeguroId = 4,
                            Descripcion = "Seguro de fianzas",
                            Nombre = "Fianzas"
                        });
                });

            modelBuilder.Entity("Seguros.API.Models.Cotizacion", b =>
                {
                    b.HasOne("Seguros.API.Models.Cliente", "Cliente")
                        .WithMany("Cotizaciones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Seguros.API.Models.TipoSeguro", "TipoSeguro")
                        .WithMany("Cotizaciones")
                        .HasForeignKey("TipoSeguroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("TipoSeguro");
                });

            modelBuilder.Entity("Seguros.API.Models.Cliente", b =>
                {
                    b.Navigation("Cotizaciones");
                });

            modelBuilder.Entity("Seguros.API.Models.TipoSeguro", b =>
                {
                    b.Navigation("Cotizaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
